elearn_web/elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elearn_web/library/urls.py
from django.urls import path
from .import views

urlpatterns = [
	path('', views.home),
]

elearn_web/users/urls.py
from django.urls import path
from . import views
app_name = "users"
urlpatterns = [
	path('login/', views.login, name='login'),
	path('register/', views.register, name='register'),
	path('logout/', views.logout, name='logout'),
]

elearn_web/library/models.py
from django.db import models

# Create your models here.

elearn_web/users/models.py
from django.db import models

# Create your models here.

elearn_web/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Signupform(UserCreationForm):
	name = forms.CharField(max_length=50)
	username = forms.EmailField(max_length=300)
	password = forms.CharField(max_length=50)
	rollno = forms.IntegerField()
	branch = forms.CharField(max_length=50)
	semester = forms.IntegerField()

class Loginform(UserCreationForm):
	username = forms.EmailField(max_length=300)
	password = forms.CharField(max_length=50)

elearn_web/library/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage


def home(request):
	if set_user!="":
		return render(request, 'library/library.html')
	# if there is a post request 
	# take the response and search that thing by name through our firestore , create an array for all the results that match and display
	return render(request, 'user/login.html')

# def upload(request):
# 	if  set_user=="":
# 		return render(request, 'user/login.html')
# 	if request.method == 'POST' and request.FILES['myfile']:
# 		fs = FileSystemStorage()
# 		filename = fs.save(myfile.name, myfile)
# 		uploaded_file_url = fs.url(filename)
# 		return render(request, 'library/simple_upload.html', {'uploaded_file_url: uploaded_file_url'})
# 	return render(request, 'library/simple_upload.html')	

#def library(request):
#
#	return render(request, 'library/library.html', {})



def search(request):
	if request.method  == 'POST':
		query=request.POST.get('q')
		if query is not None:
			resource_ref =  db.collection(u'RESOURCES')
			query_ref = resource_ref.where(u'Name', u'==', query).stream()
			arr_books = []
			arr_videos = []
			arr_links = []
			for doc in query_ref:
				dict_object = doc.to_dict()
				if (dict_object['type'] == u'videolink' ):
					arr_links.append(dict_object)
				if (dict_object['type'] == u'book pdf' ):
					arr_books.append(dict_object)
				if (dict_object['type'] == u'video' ):
					arr_videos.append(dict_object)
			return 	render(request,'library/library.html'),arr_videos,arr_books,arr_links
		else:
			return render(request,'library/library.html')
	else:
		return render(request,'library/library.html')			

elearn_web/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from google.cloud import firestore
from .forms import Signupform
from .forms import Loginform


global set_user
set_user = ""
# Add a new document
db = firestore.Client()
def register(request):
	if request.method == 'POST':
		form = Signupform(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password')
			rollno = form.cleaned_data.get('rollno')
			branch = form.cleaned_data.get('branch')
			semester = form.cleaned_data.get('semester')
			name = form.cleaned_data.get('name')

			data = {
			    u'password': raw_password,
			    u'Rollno': rollno,
			    u'name': name,
			    u'branch': branch,
			    u'semester': semester
			    
			}

			db.collection(u'USER').document(username).set(data)

			set_user = username
			return redirect('home')
		else:
			print(form.errors)

	else:
		form = Signupform()
		return render(request, 'users/signup.html',{'form': form})			

def login(request):
	
	if request.method == 'POST':
		form = Loginform(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password')
			doc_ref = db.collection(u'USER').document(username)
			try:
			    doc = doc_ref.get()
			    if (doc['password'] == raw_password):
			    	# verify and send to the home page 
			    	
			    	set_user = username
			    	return redirect('home')
			    else:
			    	# wrong user and send to the login page again
			    	set_user="" 
			    	return redirect('login')
			except google.cloud.exceptions.NotFound:
				print(u'No such document!')
	else:
		form = Loginform()	
		return render(request, 'users/login.html',{'form': form})			
	
	
def logout(request):
	set_user=""
	return render(request, 'login.html')

elearn_web/library/templates/library/library.html
<!DOCTYPE html>
<html>
<title>E-Learning</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<body >
 <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand text-white" href="{% 'library:home' %}">E-Learning</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% 'library:home' %}">Home</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% 'users:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navigation -->

    <!-- Carousel Slider -->
    <div id="carouselLogo" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselLogo" data-slide-to="0" class="active"></li>
            <li data-target="#carouselLogo" data-slide-to="1"></li>
            <li data-target="#carouselLogo" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://www.facenet.org/wp-content/themes/executive/assets/images/header.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="http://www.facenet.org/wp-content/themes/executive/assets/images/header.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="http://www.facenet.org/wp-content/themes/executive/assets/images/header.jpg" alt="First slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselLogo" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselLogo" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <br><br>
    <!-- Search Bar -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<div class="container">
    <br/>
  <div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm">
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>
                                    <!--end of col-->
                                    <div class="col">
                                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="Search topics or keywords">
                                    </div>
                                    <!--end of col-->
                                    <div class="col-auto">
                                        <button href="{% 'library:search' %}" class="btn btn-lg btn-success" type="submit">Search</button>
                                    </div>
                                    <!--end of col-->
                                </div>
                            </form>
                        </div>
                        <!--end of col-->
                    </div>
</div>
<style>
  .form-control-borderless {
    border: none;
}

.form-control-borderless:hover, .form-control-borderless:active, .form-control-borderless:focus {
    border: none;
    outline: none;
    box-shadow: none;
}
</style>
    <!-- Card -->
    <div class="container container mt-4 mb-5">
        <hr class="bg-dark mb-4 w-25">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="https://dummyimage.com/350x250/c7c7c7/000.png" alt="Card image cap">
                    <div class="card-block p-3">
                        <h4 class="card-title">Video Lectures</h4>
                        <p class="card-text">Here's a detailed section of videos, covering almost all major technical fields one tries to venture into. The section one of these lectures consists of a carefully curated list of lectures from various popular websites like Coursera, Udemy etc. The second section consists of lectures that have been created by the students and professors in the different clubs and departments of IIT Guwahati </p>
                        <a href="#" class="btn btn-primary rounded-0 mb-2">Read More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="https://dummyimage.com/350x250/c7c7c7/000.png" alt="Card image cap">
                    <div class="card-block p-3">
                        <h4 class="card-title">CSS</h4>
                        <p class="card-text">When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <a href="#" class="btn btn-primary rounded-0 mb-2">Read More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="https://dummyimage.com/350x250/c7c7c7/000.png" alt="Card image cap">
                    <div class="card-block p-3">
                        <h4 class="card-title">BOOTSTRAP</h4>
                        <p class="card-text">When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <a href="#" class="btn btn-primary rounded-0 mb-2">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Card -->
    <!-- Footer -->
    <br><br><br>
    <footer class="footer bg-dark text-white">
        <!-- Social Icons -->
        <div class="bg-primary">
            <div class="container">
                <div class="row py-4">
                    
                </div>
            </div>
        </div>
        <!-- Social Icons -->
        <!-- Footer Links -->
        <div class="container pt-5 pb-2">
            <div class="row">
                <div class="col-md-3 col-lg-4 col-xl-3">
                    <h4>E-Learn</h4>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                </div>
            </div>
        </div>
        <!-- Footer Links-->
        <!--hr class="bg-white mx-4 mt-2 mb-1"-->
    </footer>
    <!-- Footer -->
<style >
  @import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css');
.bg-dark {
    background-color: #343a40!important;
}

</style>
</body>
</html>

elearn_web/users/templates/users/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>E Learning</title>
  </head>
  <body>  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <div class="sidenav">
         <div class="login-main-text">
            <h2>Application<br> Login Page</h2>
            <p>Login or register from here to access.</p>
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form>
                  <div class="form-group">
                     <label>User Name</label>
                     <input type="text" class="form-control" placeholder="User Name">
                  </div>
                  <div class="form-group">
                     <label>Password</label>
                     <input type="password" class="form-control" placeholder="Password">
                  </div>
                  <button type="submit" href="{% url 'users:login' %}" class="btn btn-black">Login</button>
               <a type="submit" href="{% url 'users:register' %}" >Register</a>
              
               </form>

            </div>
         </div>
      </div>
  </body>
  <style>
  body {
    font-family: "Lato", sans-serif;
}



.main-head{
    height: 150px;
    background: #FFF;
   
}

.sidenav {
    height: 100%;
    background-color: #000;
    overflow-x: hidden;
    padding-top: 20px;
}


.main {
    padding: 0px 10px;
}

@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
}

@media screen and (max-width: 450px) {
    .login-form{
        margin-top: 10%;
    }

    .register-form{
        margin-top: 10%;
    }
}

@media screen and (min-width: 768px){
    .main{
        margin-left: 40%; 
    }

    .sidenav{
        width: 40%;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
    }

    .login-form{
        margin-top: 80%;
    }

    .register-form{
        margin-top: 20%;
    }
}


.login-main-text{
    margin-top: 20%;
    padding: 60px;
    color: #fff;
}

.login-main-text h2{
    font-weight: 300;
}

.btn-black{
    background-color: #000 !important;
    color: #fff;
}
  </style>
</html>

elearn_web/users/templates/users/signup.html
<!DOCTYPE html>
<html>
<title>E-Learning</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<body >
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <section>      
        <h1 class="entry-title"><span>Sign Up</span> </h1>
        <hr>
            <form class="form-horizontal" method="post" name="signup" id="signup" enctype="multipart/form-data" >    
            {% csrf_token %}    
        <div class="form-group">
          <label class="control-label col-sm-3">Email ID <span class="text-danger">*</span></label>
          <div class="col-md-8 col-sm-9">
              <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
              <input type="email" class="form-control" name="username" id="username" placeholder="Enter your Email ID" value="{{ current_name}}">
            </div>
            <small> Your Email Id is being used for ensuring the security of your account, authorization and access recovery. </small> </div>
        </div>
        
        <div class="form-group">
          <label class="control-label col-sm-3">Set Password <span class="text-danger">*</span></label>
          <div class="col-md-5 col-sm-8">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
              <input type="password" class="form-control" name="password" id="password" placeholder="Choose password (5-15 chars)" value="{{ current_name}}">
           </div>   
          </div>
        </div>
        
        <div class="form-group">
          <label class="control-label col-sm-3">Full Name <span class="text-danger">*</span></label>
          <div class="col-md-8 col-sm-9">
            <input type="text" class="form-control" name="name" id="name" placeholder="Enter your Name here" value="{{ current_name}}">
          </div>
        </div>
        
        <div class="form-group">
          <label class="control-label col-sm-3">Roll No <span class="text-danger">*</span></label>
          <div class="col-md-5 col-sm-8">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-phone"></i></span>
            <input type="number" class="form-control" name="rollno" id="rollno" placeholder="Enter your Primary contact no." value="{{ current_name}}">
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Branch <span class="text-danger">*</span></label>
          <div class="col-md-8 col-sm-9">
            <input type="text" class="form-control" name="branch" id="branch" placeholder="Enter your Branch here" value="">
          </div>
        </div>
        
        <div class="form-group">
          <label class="control-label col-sm-3">Current Semester <span class="text-danger">*</span></label>
          <div class="col-md-8 col-sm-9">
            <input type="number" class="form-control" name="semseter" id="semseter" placeholder="Enter the current Semester you are enrolled in" value="{{ current_name}}">
          </div>
        </div>

        <div class="form-group">
          <div class="col-xs-offset-3 col-md-8 col-sm-9"><span class="text-muted"><span class="label label-danger">Note:-</span> By clicking Sign Up, you agree to our <!--a href="#"-->Terms</a> and that you have read our <!--a href="#"-->Policy</a>, including our <!--a href="#"-->Cookie Use</a>.</span> </div>
        </div>

        <div class="form-group">
          <div class="col-xs-offset-3 col-xs-10">
            <input href="{% url 'users:register' %}"name="Submit" type="submit" value="Sign Up" class="btn btn-primary">
          </div>
        </div>
      </form>
    </div>
</div>
</div>

<style>

@import url(http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700);
@import url(http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700);

body {
    background: #fff;
  font-family: 'Roboto', sans-serif;
  color:#333;
  line-height: 22px;  
}
h1, h2, h3, h4, h5, h6 {
  font-family: 'Roboto Condensed', sans-serif;
  font-weight: 400;
  color:#111;
  margin-top:5px;
  margin-bottom:5px;
}
h1, h2, h3 {
  text-transform:uppercase;
}

input.upload {
    position: absolute;
    top: 0;
    right: 0;
    margin: 0;
    padding: 0;
    font-size: 12px;
    cursor: pointer;
    opacity: 1;
    filter: alpha(opacity=1);    
}

.form-inline .form-group{
    margin-left: 0;
    margin-right: 0;
}
.control-label {
    color:#333333;
}</style>
</body>
</html>